# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 885625956afe71472bc694971b0560076b58651f75b61caf3e1a4f64619ecbdb4276b960165e21b62424553fcdcf29c9dae2effa00e3431be42ba8c8349740d0

test:
  secret_key_base: 73534df661ab85d3cc45be2c11824dcf8b8bb9d46c8a6d82874150d2dc55bc874b2ad31e37a930d20f6056cfb4c2890368af7144fdc9b74aa508d48c49c6cdeb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
